#!/usr/bin/env python3
"""Generate the manuscript figures and Supplementary Figures.

Main-text panel order:
Fig. 2 glucose-focused decoupling and respiratory-disposal controls;
Fig. 3 E. coli disposal capacity -> carbon source -> mechanism -> factorial synthesis;
Fig. 4 cross-species glucose response -> routing -> yeast validation -> multi-carbon generalization.
"""
from pathlib import Path
import json, shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'figures'/'publication'; OUT.mkdir(parents=True,exist_ok=True)
# Remove only publication figures generated by this workflow; S15 is generated by its benchmark script.
for pattern in ('Fig*.png','Fig*.pdf','SuppFig*.png','SuppFig*.pdf','Supplementary_Figure_S16*.png','Supplementary_Figure_S17*.png','Supplementary_Figure_S18*.png'):
    for p in OUT.glob(pattern): p.unlink()

plt.rcParams.update({'font.family':'DejaVu Sans','font.size':9,'axes.titlesize':10.5,'axes.labelsize':9,'xtick.labelsize':8,'ytick.labelsize':8,'legend.fontsize':7.2,'axes.spines.top':False,'axes.spines.right':False,'figure.dpi':120,'savefig.dpi':400})
def panel_title(ax,letter,title): ax.set_title(rf'$\bf{{{letter.lower()}}}$  {title}',loc='left',pad=7)
def save_main(fig,stem):
    fig.savefig(OUT/f'{stem}.png',bbox_inches='tight',pad_inches=.06,dpi=400); fig.savefig(OUT/f'{stem}.pdf',bbox_inches='tight',pad_inches=.06); plt.close(fig)
def save(fig,name):
    path=OUT/name
    fig.savefig(path,bbox_inches='tight',pad_inches=.06,dpi=400)
    fig.savefig(path.with_suffix('.pdf'),bbox_inches='tight',pad_inches=.06)
    plt.close(fig)

# Canonical results
et=pd.read_csv(ROOT/'results/electron_transfer_table.tsv',sep='\t')
val=pd.read_csv(ROOT/'results/validation_battery_table.csv')
pairs=pd.read_csv(ROOT/'results/matched_pairs_all.csv')
hubs=pd.read_csv(ROOT/'results/top_hubs.csv').head(8).copy()
relay=pd.read_csv(ROOT/'results/electron_carrier_relay_by_condition.csv')
flow_summary=pd.read_csv(ROOT/'results/electron_path_summary_by_condition.csv').set_index('condition')
subsystems=pd.read_csv(ROOT/'results/fba_subsystem_comparison.csv',index_col=0)
edges=pd.read_csv(ROOT/'results/redistribution_aerobic_vs_anaerobic.csv')
terminal=pd.read_csv(ROOT/'results/electron_terminal_fates_interpreted_by_condition.csv')
condition_summary=pd.read_csv(ROOT/'results/fba_condition_summary.csv').set_index('condition')
qc=pd.read_csv(ROOT/'results/cross_species/cross_species_qc.csv')
phys=pd.read_csv(ROOT/'results/cross_species/cross_species_physiology.csv')
sal=pd.read_csv(ROOT/'results/cross_species/salmonella_oxygen_titration.csv')
pic=pd.read_csv(ROOT/'results/cross_species/pichia_oxygen_titration.csv')
comp=pd.read_csv(ROOT/'results/cross_species/electron_flux_compression_summary.csv')
accept=pd.read_csv(ROOT/'results/publication/acceptor_titration.csv')
subs=pd.read_csv(ROOT/'results/publication/substrate_flux_compression.csv')
core=pd.read_csv(ROOT/'results/publication/substrate_core_redox_contribution.csv')
mfa=pd.read_csv(ROOT/'results/publication/gonzalez_13c_mfa_electron_flux_metrics.csv')
src=pd.read_csv(ROOT/'results/publication/gonzalez_anaerobic_source_decomposition.csv')
jouhten=pd.read_csv(ROOT/'results/publication/jouhten2008_13c_mfa_electron_source_metrics.csv')
jouhten_match=pd.read_csv(ROOT/'results/publication/jouhten2008_matched_model_experiment.csv')
toya_totals=pd.read_csv(ROOT/'results/publication/toya2012_electron_source_totals.csv')
toya_decomp=pd.read_csv(ROOT/'results/publication/toya2012_electron_source_decomposition.csv')
denby_model=pd.read_csv(ROOT/'results/publication/denby2015_model_matched_states.csv')
denby_products=pd.read_csv(ROOT/'results/publication/denby2015_product_redistribution.csv')
denby_summary=json.loads((ROOT/'results/publication/denby2015_summary.json').read_text())
perrenoud=pd.read_csv(ROOT/'results/publication/perrenoud2005_acceptor_comparison.csv')
principle_pairs=pd.read_csv(ROOT/'results/publication/cross_species_carbon_acceptor_pairs.csv')
principle_feasibility=pd.read_csv(ROOT/'results/publication/cross_species_carbon_acceptor_feasibility.csv')
fromanger=pd.read_csv(ROOT/'results/publication/fromanger2010_electron_balance.csv')
baumann=pd.read_csv(ROOT/'results/publication/baumann2010_13c_mfa_electron_source_metrics.csv')
weu_glc=pd.read_csv(ROOT/'results/publication/weusthuis1994_glucose_response.csv')
weu_held=pd.read_csv(ROOT/'results/publication/weusthuis1994_maltose_heldout_predictions.csv')
weu_stats=json.loads((ROOT/'results/publication/weusthuis1994_predictive_transfer_statistics.json').read_text())
steinsiek_pred=pd.read_csv(ROOT/'results/publication/steinsiek2014_predictive_transfer_points.csv')
steinsiek_source=pd.read_csv(ROOT/'results/publication/steinsiek2014_predictive_transfer_source_choice.csv')
steinsiek_omit=pd.read_csv(ROOT/'results/publication/steinsiek2014_predictive_transfer_source_level_omission.csv')
steinsiek_stats=json.loads((ROOT/'results/publication/steinsiek2014_predictive_transfer_statistics.json').read_text())
factorial=pd.read_csv(ROOT/'results/publication/factorial_carbon_oxygen_states.csv')
scaled=pd.read_csv(ROOT/'results/publication/factorial_scaled_expansion_curves.csv')
fstats=json.loads((ROOT/'results/publication/factorial_carbon_oxygen_statistics.json').read_text())
ecom=pd.read_csv(ROOT/'results/publication/ecom4la_state_constrained_summary.csv')
steinsiek=pd.read_csv(ROOT/'data/experimental/steinsiek2014/steinsiek2014_byproducts_means.csv')
extended_acceptor=pd.read_csv(ROOT/'results/publication/extended_acceptor_functional_states.csv')
extended_acceptor_scaled=pd.read_csv(ROOT/'results/publication/extended_acceptor_scaled_multiarchitecture.csv')
extended_acceptor_stats=json.loads((ROOT/'results/publication/extended_acceptor_screen_statistics.json').read_text())
extended_carbon=pd.read_csv(ROOT/'results/publication/extended_carbon_entry_summary.csv')
extended_carbon_feas=pd.read_csv(ROOT/'results/publication/extended_carbon_entry_feasibility.csv')

# Shared cross-species order
order=['E. coli','S. cerevisiae','B. subtilis','S. enterica','K. phaffii']
state_map={'E. coli':('aerobic','anaerobic'),'S. cerevisiae':('aerobic','anaerobic'),'B. subtilis':('aerobic','anaerobic'),'S. enterica':('high-respiratory-capacity','anoxic'),'K. phaffii':('high-respiratory-capacity','severe oxygen limitation')}
comp=comp.set_index('organism').loc[order].reset_index()
org_order=['E. coli','B. subtilis','S. enterica','K. phaffii','S. cerevisiae']; markers={'E. coli':'o','B. subtilis':'s','S. enterica':'^','K. phaffii':'D','S. cerevisiae':'P'}
ord2=['glucose','fructose','galactose','xylose','gluconate','glycerol']
labelmap={'TBE029':'Parent','TBE031_bo_only':'bo-only','TBE032_bdII_only':'bd-II-only','TBE042_bdI_only':'bd-I-only'}

# ---------------- Figures 2–4 ----------------
# Main-text figures are centralized in main_figures.py so the visual contract
# (layout, typography, colors, limits and legends) is defined in one place.
from main_figures import generate_all as generate_main_figures
generate_main_figures(ROOT, OUT)

# ---------------- Supplementary figures ----------------

# Supplementary numbering:
# S1 reconstruction diagnostics;
# S2 reconstructed iML1515 electron transfer network; S3 E. coli condition diagnostics; S4 pFBA/13C-MFA validation;
# S5 13C-MFA source decomposition; S6 ECOM4LA; S7 respiratory architecture;
# S8 acceptor endpoints; S9 Denby TMAO; S10 Toya nitrate; S11 Perrenoud;
# S12 factorial response; S13 cross-species relay; S14 Baumann; S15 extended acceptors;
# S16 cross-species carbon normalization; S17 extended carbon entry; S18 Fromanger;
# S19 respiratory-architecture predictive transfer; S20 carbon-source predictive transfer.

# S2 uses the validated network generated by make_ecoli_etn_network_figure.py.
for suffix in ('png','pdf','svg'):
    asset=ROOT/'data'/'figure_assets'/f'SuppFigS2_iML1515_ETN.{suffix}'
    if not asset.exists(): raise FileNotFoundError(asset)
    shutil.copy2(asset,OUT/asset.name)

phys_diag=pd.read_csv(ROOT/'results/physiological_state_summary.csv').set_index('condition')
sca=pd.read_csv(ROOT/'results/source_carrier_sink_aerobic.csv')
scn=pd.read_csv(ROOT/'results/source_carrier_sink_anaerobic.csv')
fig,axes=plt.subplots(2,2,figsize=(10.0,7.8),constrained_layout=True)
ax=axes[0,0]
cond=['aerobic','anaerobic']; labs=['Aerobic','Anaerobic']; x=np.arange(2)
activity=np.array([flow_summary.loc[c,'total_edge_activity'] for c in cond]); q=np.array([condition_summary.loc[c,'qGLC'] for c in cond])
ax.bar(x,activity,width=.58)
for i,v in enumerate(activity): ax.text(i,v+4,f'{v:.1f}\n({v/q[i]:.2f} e$^-$ / glucose)',ha='center',fontsize=7.5)
ax.set_xticks(x,labs); ax.set_ylim(0,max(activity)*1.25); ax.set_ylabel('Cumulative electron-transfer activity\n(e$^-$ mmol gDW$^{-1}$ h$^{-1}$)'); panel_title(ax,'a','Cumulative activity')

ax=axes[0,1]
top_ids=[]
for df in (sca,scn): top_ids += df.head(6).metabolite_id.tolist()
top_ids=list(dict.fromkeys(top_ids))[:8]
def _diag_get(df,mid):
    r=df[df.metabolite_id==mid]
    return float(r.total_electron_flux.iloc[0]) if len(r) else 0.0
short={'nadh_c':'NADH','nadph_c':'NADPH','fadh2_c':'FADH$_2$','q8h2_c':'Ubiquinol-8','h2o_c':'H$_2$O','g6p_c':'Glucose-6-P','etoh_c':'Ethanol','3pg_c':'3-phosphoglycerate','succ_c':'Succinate','mal__L_c':'L-malate'}
name_map={r.metabolite_id:short.get(r.metabolite_id,r['name']) for _,r in pd.concat([sca,scn]).drop_duplicates('metabolite_id').iterrows()}
y=np.arange(len(top_ids)); w=.34
ax.barh(y-w/2,[_diag_get(sca,m) for m in top_ids],height=w,label='Aerobic')
ax.barh(y+w/2,[_diag_get(scn,m) for m in top_ids],height=w,label='Anaerobic')
ax.set_yticks(y,[name_map.get(m,m) for m in top_ids]); ax.invert_yaxis(); ax.set_xlabel('Electron-transfer activity'); ax.legend(frameon=False); panel_title(ax,'b','Dominant electron-flow nodes')

ax=axes[1,0]
products=['predicted_acetate_exchange','predicted_formate_exchange','predicted_ethanol_exchange','predicted_succinate_exchange']; plab=['Acetate','Formate','Ethanol','Succinate']; x=np.arange(4); w=.34
ax.bar(x-w/2,[phys_diag.loc['aerobic',z] for z in products],width=w,label='Aerobic')
ax.bar(x+w/2,[phys_diag.loc['anaerobic',z] for z in products],width=w,label='Anaerobic')
ax.set_xticks(x,plab,rotation=25,ha='right'); ax.set_ylabel('Predicted secretion flux\n(mmol gDW$^{-1}$ h$^{-1}$)'); ax.legend(frameon=False); panel_title(ax,'c','pFBA-predicted products')

# Supplementary carrier-relay panel.
ax=axes[1,1]
picks=[('nadh_c','NADH'),('nadph_c','NADPH'),('fadh2_c','FADH$_2$'),('q8h2_c','Ubiquinol-8')]
names=[]; aa=[]; bb=[]
for cid,name in picks:
    gg=relay[relay.carrier==cid]
    if len(gg):
        names.append(name)
        aa.append(float(gg[gg.condition=='aerobic'].relay_throughflow.iloc[0]))
        bb.append(float(gg[gg.condition=='anaerobic'].relay_throughflow.iloc[0]))
x=np.arange(len(names)); w=.36
ax.bar(x-w/2,aa,w,label='Aerobic'); ax.bar(x+w/2,bb,w,label='Anaerobic')
ax.set_xticks(x,names,rotation=25,ha='right'); ax.set_ylabel('Carrier relay flux\n(e$^-$ mmol gDW$^{-1}$ h$^{-1}$)')
ax.legend(frameon=False); panel_title(ax,'d','Major redox-carrier relay')
save(fig,'SuppFigS3_ecoli_diagnostics.png')

car=pd.read_csv(ROOT/'results/cross_species/cross_species_carrier_relay.csv')
fig,ax=plt.subplots(figsize=(9.2,4.8),constrained_layout=True)
high=[]; low=[]
for org in order:
    hi,lo=state_map[org]
    sub=car[(car.organism==org)&(car.carrier.str.lower()=='nadh')]
    high.append(float(sub[sub.condition==hi].relay.iloc[0]))
    low.append(float(sub[sub.condition==lo].relay.iloc[0]))
x=np.arange(len(order)); width=0.38
ax.bar(x-width/2,high,width,label='High respiratory capacity')
ax.bar(x+width/2,low,width,label='Low O$_2$ / anoxic')
ax.set_xticks(x,order,rotation=20,ha='right')
ax.set_ylabel('NADH relay flux\n(e$^-$ mmol gDW$^{-1}$ h$^{-1}$)')
ax.legend(frameon=False,fontsize=8)
save(fig,'SuppFigS13_cross_species_relay.png')

endp=pd.read_csv(ROOT/'results/publication/acceptor_endpoints.csv')
fig,axs=plt.subplots(1,2,figsize=(9.4,3.8),constrained_layout=True)
x=np.arange(len(endp))
axs[0].bar(x,endp.net_per_glucose); axs[0].set_xticks(x,endp.acceptor,rotation=30,ha='right'); axs[0].set_ylabel('Net electron flux (e$^-$ per glucose)'); panel_title(axs[0],'a','Alternative acceptor endpoints')
axs[1].bar(x,endp.cumulative_per_glucose); axs[1].set_xticks(x,endp.acceptor,rotation=30,ha='right'); axs[1].set_ylabel('Cumulative electron-transfer activity\n(e$^-$ per glucose)'); panel_title(axs[1],'b','Relay can increase before net flux')
save(fig,'SuppFigS8_acceptor_endpoints.png')

subcomp=pd.read_csv(ROOT/'results/publication/substrate_flux_compression.csv').set_index('substrate'); comp=[]
for _,row in mfa.iterrows():
    comp.append((row.substrate,row.state,float(subcomp.loc[row.substrate,'net_per_glucose_oxygen' if row.state=='aerobic' else 'net_per_glucose_anoxic']),float(row.net_e_per_substrate)))
fig,axs=plt.subplots(2,2,figsize=(10.0,7.8),constrained_layout=True)
ax=axs[0,0]
for substrate in ['glucose','xylose']:
    pts=[z for z in comp if z[0]==substrate]
    ax.scatter([z[2] for z in pts],[z[3] for z in pts],s=45,label=substrate.capitalize())
    for _,st,xv,yv in pts:
        ax.annotate('Aer.' if st=='aerobic' else 'Anox.',(xv,yv),xytext=(3,3),textcoords='offset points',fontsize=7)
lim=[3,12]; ax.plot(lim,lim,lw=1); ax.set_xlim(lim); ax.set_ylim(lim)
ax.set_xlabel('pFBA/ETN prediction (e$^-$ per substrate)')
ax.set_ylabel('$^{13}$C-MFA-derived electron flux\n(e$^-$ per substrate)')
ax.legend(frameon=False); panel_title(ax,'a','Experimental flux maps reproduce compression')

# Normalize the experimental 2×2 glucose/xylose comparison by carbon number and
# by total substrate degree of reduction.  Conservative reaction-flux envelopes
# are propagated by the same deterministic scaling.
for ax, value, lo, hi, ylabel, letter, title in [
    (axs[0,1],'net_e_per_C','net_e_lb_per_C','net_e_ub_per_C','Electron flux (e$^-$ per C)','b','Compression persists per carbon'),
    (axs[1,0],'net_e_fraction_of_substrate_gamma','net_e_fraction_gamma_lb','net_e_fraction_gamma_ub',r'Electron flux / substrate $\gamma$','c','Compression persists per reducing power'),
]:
    x=np.arange(2); w=.32
    for j,state in enumerate(['aerobic','anaerobic']):
        vals=[]; lows=[]; highs=[]
        for substrate in ['glucose','xylose']:
            r=mfa[(mfa.substrate==substrate)&(mfa.state==state)].iloc[0]
            vals.append(float(r[value])); lows.append(float(r[lo])); highs.append(float(r[hi]))
        vals=np.asarray(vals); lows=np.asarray(lows); highs=np.asarray(highs)
        xpos=x+(j-.5)*w
        ax.bar(xpos,vals,width=w,label='Aerobic' if state=='aerobic' else 'Anaerobic')
        ax.errorbar(xpos,vals,yerr=np.vstack([vals-lows,highs-vals]),fmt='none',ecolor='black',capsize=2,lw=.8)
    ax.set_xticks(x,['Glucose','Xylose']); ax.set_ylabel(ylabel); panel_title(ax,letter,title)
axs[0,1].legend(frameon=False,fontsize=7)

# Supplementary absolute per-glucose comparison.
ax=axs[1,1]
g=mfa[mfa.substrate=='glucose'].set_index('state').loc[['aerobic','anaerobic']]
x=np.arange(2); vals=g.net_e_per_substrate.to_numpy(float)
lows=g.net_e_lb_envelope.to_numpy(float); highs=g.net_e_ub_envelope.to_numpy(float)
ax.bar(x,vals,width=.58)
ax.errorbar(x,vals,yerr=np.vstack([vals-lows,highs-vals]),fmt='none',ecolor='black',capsize=2,lw=.8)
ax.set_xticks(x,['Aerobic','Anaerobic']); ax.set_ylabel('$^{13}$C-MFA-derived net electron flux\n(e$^-$ per glucose)')
panel_title(ax,'d','Independent glucose flux maps')
save(fig,'SuppFigS4_pFBA_vs_13C_MFA.png')

fig,axs=plt.subplots(1,2,figsize=(9.4,4.1),constrained_layout=True)
for ax,cond in zip(axs,['Anaerobic glucose','Anaerobic xylose']):
    ss=src[src.condition==cond].sort_values('electron_source_per_substrate')
    ax.barh(ss.source,ss.electron_source_per_substrate)
    ax.set_xlabel('Electron-source flux (e$^-$ per substrate)')
    ax.set_title(cond)
save(fig,'SuppFigS5_13C_MFA_source_decomposition.png')


# S2: detailed reconstruction statistics supporting the electron-transfer reconstruction.
status_order=["non_redox","not_applicable","redox","unscorable","ambiguous"]
status_labels=["Non-redox","Struct. excluded","Redox","Chem. unscorable","Ambiguous"]
status_counts=et["redox_status"].value_counts().reindex(status_order,fill_value=0).astype(int)
stoich=(pd.to_numeric(et.loc[et["redox_status"].eq("redox"),"n_electrons_transferred"],errors="raise").astype(int).value_counts().sort_index())
pair_groups=pd.Series({"Seed matching":int(pairs["source"].eq("curated_cofactor_list").sum()),"Formula / stoichiometry":int(pairs["source"].eq("ab_initio_formula_match").sum())})
fig,axs=plt.subplots(2,2,figsize=(10.0,7.4),constrained_layout=True)
ax=axs[0,0]; ax.bar(np.arange(5),status_counts.values); ax.set_yscale("log"); ax.set_xticks(np.arange(5),status_labels,rotation=35,ha="right"); ax.set_ylabel("Reactions (log scale)"); panel_title(ax,"a","Model-wide classification")
for i,v in enumerate(status_counts.values): ax.text(i,v*1.08,str(int(v)),ha="center",fontsize=8)
ax=axs[0,1]; ax.bar(np.arange(len(stoich)),stoich.values); ax.set_xticks(np.arange(len(stoich)),[str(x) for x in stoich.index]); ax.set_xlabel("e$^-$ per turnover"); ax.set_ylabel("Redox reactions"); panel_title(ax,"b","Electron-transfer stoichiometry")
ax=axs[1,0]; ax.bar(np.arange(2),pair_groups.values); ax.set_xticks(np.arange(2),pair_groups.index); ax.set_ylabel("Matched pair instances"); panel_title(ax,"c","Origin of matched redox pairs")
name_map={"nadh_c":"NADH","nadph_c":"NADPH","h2o_c":"H$_2$O","q8h2_c":"Ubiquinol-8","mql8_c":"Menaquinol-8","fadh2_c":"FADH$_2$","2dmmql8_c":"DMK-8H$_2$","succ_c":"Succinate"}
h=hubs.iloc[::-1].copy(); labels=[name_map.get(mid,name) for mid,name in zip(h.metabolite_id,h.name)]; ax=axs[1,1]; ax.barh(np.arange(len(h)),h.weighted_degree_electrons); ax.set_yticks(np.arange(len(h)),labels); ax.set_xlabel("Electron-weighted connectivity"); panel_title(ax,"d","Leading electron-bearing metabolites")
save(fig,"SuppFigS1_reconstruction_details.png")

# S10: Toya 2012 nitrate 13C-flux source architecture.
fig,axs=plt.subplots(1,2,figsize=(10.0,4.2),constrained_layout=True)
order_t=["WT anaerobic","WT nitrate","ArcA nitrate"]
tt=toya_totals.set_index("condition").loc[order_t].reset_index(); x=np.arange(len(tt))
y=tt.source_e_per_glucose.to_numpy(); yerr=np.vstack([y-tt.conservative_low.to_numpy(),tt.conservative_high.to_numpy()-y])
axs[0].errorbar(x,y,yerr=yerr,fmt="o",capsize=3,ms=6); axs[0].set_xticks(x,["WT anaerobic","WT + nitrate","ΔarcA + nitrate"],rotation=20,ha="right"); axs[0].set_ylabel("Electron generation\n(e$^-$ per glucose)"); panel_title(axs[0],"a","Nitrate increases electron generation")
axs[0].text(.02,.03,"Independent propagation of marginal flux limits",transform=axs[0].transAxes,fontsize=6.7)
classes=["Glycolysis","Oxidative PPP","PDH","Oxidative TCA"]; bottom=np.zeros(3)
for cls in classes:
    vals=[float(toya_decomp[(toya_decomp.condition==c)&(toya_decomp.source_class==cls)].e_per_glucose.iloc[0]) for c in order_t]
    axs[1].bar(x,vals,bottom=bottom,label=cls); bottom+=np.asarray(vals)
axs[1].set_xticks(x,["WT anaerobic","WT + nitrate","ΔarcA + nitrate"],rotation=20,ha="right"); axs[1].set_ylabel("Electron-source contribution\n(e$^-$ per glucose)"); axs[1].legend(frameon=False,fontsize=6.5); panel_title(axs[1],"b","Oxidative pathways account for the expansion")
save(fig,"SuppFigS10_Toya2012_nitrate_source_architecture.png")

# S9: Denby 2015 TMAO validation and extracellular-product redistribution.
fig,axs=plt.subplots(1,2,figsize=(10.0,4.2),constrained_layout=True)
dm=denby_model.set_index("condition"); x=np.arange(2); model_vals=[float(dm.loc["fermentation","net_per_glucose"]),float(dm.loc["tmao_matched","net_per_glucose"])]
axs[0].bar(x,model_vals,width=.58,label="iML1515/ETN net flux")
axs[0].errorbar([1],[denby_summary["reported_source_generation_e_per_glucose"]],fmt="o",mfc="white",mec="black",ms=7,lw=0,label="Experimental source balance")
axs[0].errorbar([1],[denby_summary["measured_terminal_delivery_e_per_glucose"]],yerr=[denby_summary["measured_terminal_delivery_e_sd_per_glucose"]],fmt="^",mfc="white",mec="black",ecolor="black",capsize=3,ms=7,label="Measured TMAO delivery")
axs[0].set_xticks(x,["Fermentation","TMAO respiration"]); axs[0].set_ylabel("Electron-flux observable\n(e$^-$ per glucose)"); axs[0].set_ylim(0,7.35); axs[0].legend(frameon=False,fontsize=6.4); panel_title(axs[0],"a","Independent sink-side validation")
pp=denby_products.set_index("metabolite").loc[["acetate","formate","ethanol","succinate"]].reset_index(); xx=np.arange(len(pp)); w=.34
axs[1].bar(xx-w/2,pp.experimental_fold,width=w,label="Experiment"); axs[1].bar(xx+w/2,pp.model_fold,width=w,label="Matched model"); axs[1].axhline(1,lw=.8); axs[1].set_xticks(xx,[m.capitalize() for m in pp.metabolite],rotation=20,ha="right"); axs[1].set_ylabel("TMAO / fermentative state ratio"); axs[1].legend(frameon=False); panel_title(axs[1],"b","Product redistribution has the same direction")
save(fig,"SuppFigS9_Denby2015_TMAO_validation.png")

# S11: Perrenoud & Sauer 2005 qualitative acceptor contrast.
fig,axs=plt.subplots(1,2,figsize=(9.6,4.0),constrained_layout=True)
pord=["strict anaerobic","nitrate","DMSO"]; pp=perrenoud.set_index("experimental_condition").loc[pord].reset_index(); x=np.arange(3)
axs[0].bar(x,pp.reported_respiratory_cyclic_TCA_flux_mmol_g_h); axs[0].set_xticks(x,["No acceptor","Nitrate","DMSO"]); axs[0].set_ylabel("Reported respiratory cyclic TCA flux\n(mmol g$^{-1}$ h$^{-1}$)"); panel_title(axs[0],"a","Nitrate, but not DMSO, opens cyclic TCA flux")
axs[1].bar(x,pp.model_net_e_per_glucose); axs[1].set_xticks(x,["No acceptor","Nitrate","DMSO"]); axs[1].set_ylabel("Model net electron flux\n(e$^-$ per glucose)"); panel_title(axs[1],"b","Standardized model comparison")
axs[1].text(.02,.03,"Equal uptake cap = 10; qualitative only, not matched to 40 mM medium",transform=axs[1].transAxes,fontsize=6.6)
save(fig,"SuppFigS11_Perrenoud2005_acceptor_routing.png")

# S16: cross-species generalization and normalization robustness of the baseline state.
fig,axs=plt.subplots(2,2,figsize=(10.6,8.2),constrained_layout=True)
ax=axs[0,0]
for org in org_order:
    g=principle_pairs[principle_pairs.organism==org]
    ax.scatter(g.low_net_per_substrate,g.high_net_per_substrate,s=42,marker=markers[org],label=org)
lim=[1.7,13.3]; ax.plot(lim,lim,ls='--',lw=1); ax.set_xlim(lim); ax.set_ylim(lim)
ax.set_xlabel('Electron flux at low disposal capacity\n(e$^-$ per substrate)'); ax.set_ylabel('Electron flux at high disposal capacity\n(e$^-$ per substrate)'); ax.legend(frameon=False,fontsize=6.5); panel_title(ax,'a','Every feasible pair expands with disposal capacity')

sub_abbr={'glucose':'Glc','fructose':'Fru','galactose':'Gal','xylose':'Xyl','gluconate':'Gln','glycerol':'Gly'}
for ax,col,ylabel,letter,title in [
    (axs[0,1],'low_e_per_C','Electron flux at low disposal capacity\n(e$^-$ per carbon)','b','Baseline variation after carbon normalization'),
    (axs[1,0],'low_fraction_substrate_gamma',r'Electron flux at low disposal capacity / substrate $\gamma$','c','Baseline variation after reducing-power normalization'),
]:
    for i,org in enumerate(org_order):
        g=principle_pairs[principle_pairs.organism==org].sort_values('substrate')
        # Small deterministic x offsets separate substrates without implying replication.
        offs=np.linspace(-.17,.17,len(g)) if len(g)>1 else np.array([0.0])
        ax.scatter(i+offs,g[col],s=30)
        for off,(_,r) in zip(offs,g.iterrows()):
            ax.annotate(sub_abbr.get(r.substrate,r.substrate[:3]),(i+off,r[col]),xytext=(2,2),textcoords='offset points',fontsize=5.5)
    ax.set_xticks(np.arange(len(org_order)),['E. coli','B. sub.','S. ent.','K. pha.','S. cer.'],rotation=20,ha='right'); ax.set_ylabel(ylabel); panel_title(ax,letter,title)

ax=axs[1,1]
c2=core.set_index('substrate').loc[ord2].reset_index(); ax.scatter(c2.selected_e_per_substrate,c2.net_e_per_substrate,s=45); lim2=[2.2,4.3]; ax.plot(lim2,lim2,lw=1); ax.set_xlim(lim2); ax.set_ylim(lim2)
for _,row in c2.iterrows():
    if row.substrate in ['xylose','gluconate','glycerol']: ax.annotate(row.substrate,(row.selected_e_per_substrate,row.net_e_per_substrate),xytext=(4,4),textcoords='offset points',fontsize=7)
ax.set_xlabel('Dominant core-reaction contribution\n(e$^-$ per substrate)'); ax.set_ylabel('Genome-scale anoxic electron flux\n(e$^-$ per substrate)'); panel_title(ax,'d','E. coli baseline states arise from a compact redox backbone')
save(fig,'SuppFigS16_cross_species_carbon_acceptor_principle.png')

# S18: Fromanger et al. native-yeast whole-cell electron-equivalent validation.
fig,axes=plt.subplots(1,2,figsize=(10.4,4.2),constrained_layout=True)
ax=axes[0]; panel_title(ax,'a','Electron delivery to oxygen rises on both carbon sources')
for substrate,marker,label in [('glucose','o','Glucose'),('xylose','s','Xylose')]:
    g=fromanger[fromanger.substrate==substrate].sort_values('specific_OUR_mmol_O2_gDCW_h')
    ax.plot(g.specific_OUR_mmol_O2_gDCW_h,g.electron_to_O2_pct,marker=marker,lw=1.4,label=label)
    low=(g.electron_to_O2_pct-g.electron_to_O2_pct_acid_gamma_low).abs(); high=(g.electron_to_O2_pct_acid_gamma_high-g.electron_to_O2_pct).abs()
    ax.errorbar(g.specific_OUR_mmol_O2_gDCW_h,g.electron_to_O2_pct,yerr=[low,high],fmt='none',capsize=2,lw=.8)
ax.set_xlabel('Specific O$_2$ uptake (mmol gDCW$^{-1}$ h$^{-1}$)'); ax.set_ylabel('Substrate electron equivalents delivered to O$_2$ (%)'); ax.legend(frameon=False)
ax=axes[1]; panel_title(ax,'b','Aerobic balance agrees with an independent RQ estimate')
a=fromanger[fromanger.state_type=='aerobic_reference'].set_index('substrate').loc[['glucose','xylose']]
x=np.arange(2); w=.34
ax.bar(x-w/2,a.electron_to_O2_pct,width=w,label='Product / biomass redox balance')
ax.bar(x+w/2,a.aerobic_O2_pct_from_CO2_RQ,width=w,label='CO$_2$ / RQ')
ax.set_xticks(x,['Glucose','Xylose']); ax.set_ylabel('Substrate electron equivalents delivered to O$_2$ (%)'); ax.set_ylim(0,42); ax.legend(frameon=False,fontsize=7)
save(fig,'SuppFigS18_fromanger2010_electron_balance.png')



# S15: expanded cross-species terminal-acceptor screen.
fig,axs=plt.subplots(1,2,figsize=(10.6,4.3),constrained_layout=True)
noncarbon=extended_acceptor[(extended_acceptor.status=='functional') & (~extended_acceptor.carbon_bearing)].copy()
for org in org_order:
    g=noncarbon[noncarbon.organism==org]
    if len(g):
        axs[0].scatter(g.additional_carbon_oxidation,g.electron_flux_expansion,s=42,marker=markers.get(org,'o'),label=org)
axs[0].set_xlabel('Additional carbon oxidation\n(ΔCO$_2$ per glucose)'); axs[0].set_ylabel('Electron-flux expansion\n(e$^-$ per glucose)')
axs[0].legend(frameon=False,fontsize=6.0); panel_title(axs[0],'a',f'Across all non-carbon acceptors: r = {extended_acceptor_stats["pooled_expansion_vs_additional_carbon_oxidation"]["pearson_r"]:.3f}')
for org in ['E. coli','B. subtilis','S. enterica']:
    g=extended_acceptor_scaled[extended_acceptor_scaled.organism==org]
    axs[1].scatter(g.oxidation_scaled,g.expansion_scaled,s=46,marker=markers.get(org,'o'),label=org)
axs[1].plot([0,1.04],[0,1.04],ls='--',lw=1); axs[1].set_xlim(-.03,1.08); axs[1].set_ylim(-.03,1.08)
axs[1].set_xlabel('Within-architecture scaled\nadditional carbon oxidation'); axs[1].set_ylabel('Within-architecture scaled\nelectron-flux expansion')
axs[1].legend(frameon=False,fontsize=6.2); panel_title(axs[1],'b',f'Multi-acceptor architectures collapse: r = {extended_acceptor_stats["scaled_multiarchitecture_expansion_vs_oxidation"]["pearson_r"]:.3f}')
save(fig,'SuppFigS15_extended_terminal_acceptor_generality.png')

# S17: extended carbon-entry coverage beyond the paired-state core set.
fig,axs=plt.subplots(1,2,figsize=(10.8,4.4),constrained_layout=True)
orgs=['E. coli','B. subtilis','S. enterica','K. phaffii','S. cerevisiae']; subs_ext=['acetate','pyruvate','succinate']
mat=np.zeros((len(orgs),len(subs_ext)),dtype=int)
for i,org in enumerate(orgs):
    for j,sub in enumerate(subs_ext):
        g=extended_carbon_feas[(extended_carbon_feas.organism==org)&(extended_carbon_feas.substrate==sub)]
        high=bool(((g.state=='high-respiratory-capacity')&(g.status=='feasible')).any())
        low=bool(((g.state=='low-respiratory-capacity')&(g.status=='feasible')).any())
        mat[i,j]=2 if (high and low) else (1 if high else 0)
im=axs[0].imshow(mat,aspect='auto',vmin=0,vmax=2,cmap='viridis')
axs[0].set_xticks(range(3),['Acetate\n(acetyl-CoA)','Pyruvate\n(pyruvate node)','Succinate\n(TCA)']); axs[0].set_yticks(range(len(orgs)),orgs)
for i in range(len(orgs)):
    for j in range(3):
        txt={0:'Unavailable /\nno oxic state',1:'Oxic only',2:'Paired'}[mat[i,j]]
        axs[0].text(j,i,txt,ha='center',va='center',fontsize=6.4,color='white' if mat[i,j]>0 else 'black')
panel_title(axs[0],'a','Central entry points are predominantly respiration dependent')
# High respiratory capacity net electron flux for feasible states.
for org in orgs:
    g=extended_carbon[extended_carbon.organism==org]
    if len(g):
        xx=[subs_ext.index(x) for x in g.substrate]
        axs[1].scatter(xx,g.high_net_e_per_substrate,s=45,marker=markers.get(org,'o'),label=org)
axs[1].set_xticks(range(3),['Acetate','Pyruvate','Succinate']); axs[1].set_ylabel('Net electron flux at high disposal capacity\n(e$^-$ per substrate)'); axs[1].legend(frameon=False,fontsize=6.0)
panel_title(axs[1],'b','Extended entry-point coverage at high disposal capacity')
save(fig,'SuppFigS17_extended_carbon_entry_coverage.png')

# S6: ECOM4LA direct measurements, isotope observables and model-completion robustness.
rob=pd.read_csv(ROOT/'results/publication/constraint_robustness.csv'); iso=pd.read_csv(ROOT/'results/publication/ecom4la_published_13C_checks.csv')
fig,axs=plt.subplots(2,3,figsize=(12.6,7.8),constrained_layout=True)
ax=axs[0,0]; x=np.arange(2); w=.34; ee=ecom.set_index('condition'); ax.bar(x-w/2,[ee.loc['WT_oxic','qGLC'],ee.loc['ECOM4LA_oxic','qGLC']],w,label='Glucose uptake'); ax.bar(x+w/2,[ee.loc['WT_oxic','qO2'],ee.loc['ECOM4LA_oxic','qO2']],w,label='O$_2$ uptake'); ax.set_xticks(x,['WT oxic','ECOM4LA oxic']); ax.set_ylabel('Measured uptake (mmol gDW$^{-1}$ h$^{-1}$)'); ax.legend(frameon=False); panel_title(ax,'a','Measured uptake')
ax=axs[0,1]; metrics=['e_per_glucose','effective_transfer_depth','respiratory_fraction']; labels=['Net e$^-$ / glucose','Transfer depth','Respiratory fraction']; wt=ee.loc['WT_oxic']; mut=ee.loc['ECOM4LA_oxic']; rel=[100*mut[m]/wt[m] for m in metrics]; ax.bar(np.arange(3),rel); ax.axhline(100,ls='--',lw=.8); ax.set_xticks(np.arange(3),labels,rotation=20,ha='right'); ax.set_ylabel('ECOM4LA relative to WT (%)'); panel_title(ax,'b','Electron-economy observables')
ax=axs[0,2]; ii=iso.set_index('metric'); use=['oxidative_PPP_absolute','TCA_contribution_to_OAA','oxidative_PPP_relative_to_glycolysis']; vals=[100*ii.loc[m,'ECOM4LA_oxic']/ii.loc[m,'WT_oxic'] for m in use]; ax.bar(np.arange(3),vals); ax.set_xticks(np.arange(3),['Oxidative PPP','TCA → OAA','OxPPP / glycolysis'],rotation=20,ha='right'); ax.set_ylabel('ECOM4LA relative to WT (%)'); panel_title(ax,'c','$^{13}$C-derived oxidative observables')
ax=axs[1,0]; rr=rob.pivot(index='state',columns='strict_products',values='e_per_glc').loc[['WT','ECOM4LA']]; x=np.arange(2); ax.bar(x-.18,rr[True],.36,label='Primary constraints'); ax.bar(x+.18,rr[False],.36,label='Unreported products allowed'); ax.set_xticks(x,['WT','ECOM4LA']); ax.set_ylabel('Net electron flux (e$^-$ per glucose)'); ax.legend(frameon=False,fontsize=6.5); panel_title(ax,'d','Secretion-bound robustness')

# Supplementary net-flux comparison.
ax=axs[1,1]
subcomp=pd.read_csv(ROOT/'results/publication/substrate_flux_compression.csv').set_index('substrate')
vals=[float(ee.loc['WT_oxic','e_per_glucose']),float(ee.loc['ECOM4LA_oxic','e_per_glucose']),float(subcomp.loc['glucose','net_per_glucose_anoxic'])]
errs=[0.33603654502223584,0.024706601917477932,0.0]
x=np.arange(3); ax.bar(x,vals,width=.62)
ax.errorbar(x[:2],vals[:2],yerr=errs[:2],fmt='none',ecolor='black',capsize=2,lw=.8)
ax.set_xticks(x,['WT oxic','ECOM4LA oxic','Zero respiratory capacity']); ax.set_ylabel('Net electron flux (e$^-$ per glucose)'); ax.set_ylim(0,13)
for i,(v,e) in enumerate(zip(vals,errs)): ax.text(i,v+e+.12,f'{v:.2f}',ha='center',fontsize=7)
panel_title(ax,'e','Net electron-flux comparison')
axs[1,2].axis('off')
save(fig,'SuppFigS6_ECOM4LA_respiratory_disposal.png')

# S7: independent respiratory-architecture controls.
anand=pd.read_csv(ROOT/'data/experimental/anand2022/anand2022_replicate_phenotypes.csv')
fig,axs=plt.subplots(1,2,figsize=(9.2,4.2),constrained_layout=True)
ax=axs[0]
for s,g in steinsiek.groupby('strain'): g=g.sort_values('aerobiosis_percent'); ax.plot(g.aerobiosis_percent,g.acetate_mean,marker='o',lw=1.2,label=labelmap.get(s,s))
ax.set_xlabel('Aerobiosis (%)'); ax.set_ylabel('Acetate formation'); ax.legend(frameon=False,fontsize=6.0); panel_title(ax,'a','Terminal-oxidase architecture × oxygen')
ax=axs[1]; summ=anand.groupby(['architecture','state']).acetate_carbon_fraction.agg(['mean','std']).reset_index(); arch=['1H','3H','2H','4H']; xx=np.arange(4); w=.36
for off,state in [(-w/2,'unevolved'),(w/2,'evolved')]:
 g=summ[summ.state==state].set_index('architecture').loc[arch]; ax.bar(xx+off,g['mean'],w,yerr=g['std'],capsize=2,label=state.capitalize())
ax.set_xticks(xx,arch); ax.set_ylabel('Acetate carbon fraction'); ax.legend(frameon=False); panel_title(ax,'b','Architecture signature persists after evolution')
save(fig,'SuppFigS7_respiratory_architecture_controls.png')

# S12: complete E. coli factorial response surface.
fig,axs=plt.subplots(2,2,figsize=(9.0,8.0),constrained_layout=True)
ax=axs[0,0]
for sub in ord2:
 g=factorial[factorial.substrate==sub].sort_values('oxygen_cap'); ax.plot(g.oxygen_cap,g.net_per_substrate,marker='o',lw=1.2,label=sub.capitalize())
ax.set_xlabel('O$_2$ uptake capacity'); ax.set_ylabel('Net electron flux (e$^-$ / substrate)'); ax.legend(frameon=False,fontsize=6.4,ncol=2); panel_title(ax,'a','Complete 42-state response surface')
ax=axs[0,1]
for sub in ord2:
 g=scaled[scaled.substrate==sub].sort_values('oxygen_cap'); ax.plot(g.oxygen_cap,g.scaled_expansion,marker='o',lw=1.2,label=sub.capitalize())
ax.set_xlabel('O$_2$ uptake capacity'); ax.set_ylabel('Scaled expansion'); panel_title(ax,'b','Baseline-subtracted response curves')
ax=axs[1,0]; cats=['Carbon source','O$_2$ capacity','Interaction']; vals=[fstats['raw']['substrate_pct'],fstats['raw']['oxygen_pct'],fstats['raw']['interaction_pct']]; ax.bar(np.arange(3),vals); ax.set_xticks(np.arange(3),cats,rotation=20,ha='right'); ax.set_ylabel('Variance explained (%)'); ax.set_ylim(0,100); panel_title(ax,'c','Descriptive variance decomposition')
ax=axs[1,1]; labs=['Raw','Per carbon',r'Per substrate $\gamma$']; vals=[fstats['raw']['interaction_pct'],fstats['per_carbon']['interaction_pct'],fstats['per_gamma']['interaction_pct']]; ax.bar(np.arange(3),vals); ax.set_xticks(np.arange(3),labs,rotation=20,ha='right'); ax.set_ylabel('Interaction variance (%)'); ax.set_ylim(0,max(vals)*1.25); panel_title(ax,'d','Interaction remains small after normalization')
save(fig,'SuppFigS12_factorial_response_surface.png')


# S14: K. phaffii 13C-MFA oxygen-gradient validation.
fig,axes=plt.subplots(1,2,figsize=(9.8,4.0),constrained_layout=True)
ax=axes[0]
for strain,marker,label in [('Control','o','Control'),('Fab-expressing','s','Fab-expressing')]:
    g=baumann[baumann.strain==strain].sort_values('oxygen_inlet_percent')
    ax.errorbar(g.oxygen_inlet_percent,g.electron_source_per_glucose,yerr=g.propagated_sd_e_per_glucose,marker=marker,lw=1.3,capsize=2.5,label=label)
ax.set_xlabel('Inlet O$_2$ (%)'); ax.set_ylabel('Electron generation\n(e$^-$ per glucose)'); ax.legend(frameon=False); panel_title(ax,'a','Electron generation per glucose falls with oxygen restriction')
ax=axes[1]
for strain,marker,label in [('Control','o','Control'),('Fab-expressing','s','Fab-expressing')]:
    g=baumann[baumann.strain==strain].sort_values('oxygen_inlet_percent')
    ax.plot(g.oxygen_inlet_percent,g.glucose_uptake_mmol_gDCW_h,marker=marker,lw=1.3,label=label)
ax.set_xlabel('Inlet O$_2$ (%)'); ax.set_ylabel('Glucose uptake\n(mmol gDCW$^{-1}$ h$^{-1}$)'); ax.legend(frameon=False); panel_title(ax,'b','Glucose uptake rises as oxygen is restricted')
save(fig,'SuppFigS14_Baumann2010_oxygen_gradient.png')

# S19: predictive transfer across respiratory architectures.
fig,axs=plt.subplots(2,2,figsize=(10.2,8.0),constrained_layout=True)
colors={'TBE031_bo_only':'#ff7f0e','TBE032_bdII_only':'#2ca02c','TBE042_bdI_only':'#9467bd'}
ax=axs[0,0]
for target,color in colors.items():
    g=steinsiek_pred[steinsiek_pred.target_architecture==target].sort_values('aerobiosis_percent')
    ax.plot(g.aerobiosis_percent,g.predicted_acetate_mmol_gDW_h,color=color,lw=1.4)
    anchors=g[g.role=='scaling_endpoint']; held=g[g.role=='held_out_prediction']
    ax.scatter(anchors.aerobiosis_percent,anchors.observed_acetate_mmol_gDW_h,s=42,marker='s',color=color)
    ax.scatter(held.aerobiosis_percent,held.observed_acetate_mmol_gDW_h,s=42,facecolor='white',edgecolor=color,lw=1.3)
ax.set_xlabel('Aerobiosis (%)'); ax.set_ylabel('Acetate formation\n(mmol gDW$^{-1}$ h$^{-1}$)')
panel_title(ax,'a','Parental response predicts single-oxidase strains')
ax.text(.04,.05,f'$R^2_{{pred}}$ = {steinsiek_stats["predictive_r2"]:.3f}\nRMSE = {steinsiek_stats["rmse_mmol_gDW_h"]:.2f}',transform=ax.transAxes,fontsize=7.2)

ax=axs[0,1]; held=steinsiek_pred[steinsiek_pred.role=='held_out_prediction']
lim=[0,6.4]; ax.plot(lim,lim,ls='--',lw=1,color='black')
for target,color in colors.items():
    g=held[held.target_architecture==target]
    ax.scatter(g.observed_acetate_mmol_gDW_h,g.predicted_acetate_mmol_gDW_h,s=42,label=labelmap[target],color=color)
ax.set_xlim(lim); ax.set_ylim(lim); ax.set_xlabel('Observed acetate formation'); ax.set_ylabel('Predicted acetate formation')
ax.legend(frameon=False,fontsize=6.5); panel_title(ax,'b','Twelve held-out intermediate states')

ax=axs[1,0]; ss=steinsiek_source.copy(); xx=np.arange(len(ss))
ax.bar(xx,ss.predictive_r2); ax.set_xticks(xx,[labelmap.get(x,x) for x in ss.source_architecture],rotation=25,ha='right')
ax.set_ylabel('Predictive $R^2$'); ax.set_ylim(0,1.0); panel_title(ax,'c','Source-architecture robustness')

ax=axs[1,1]; xx=np.arange(len(steinsiek_omit)); ax.bar(xx,steinsiek_omit.predictive_r2)
ax.set_xticks(xx,[f'{int(x)}%' for x in steinsiek_omit.omitted_source_level_percent]); ax.set_xlabel('Omitted parental response level')
ax.set_ylabel('Predictive $R^2$'); ax.set_ylim(0,1.0); panel_title(ax,'d','Source-level omission sensitivity')
ax.text(.04,.06,f'Rank-one variance = {steinsiek_stats["rank_one_baseline_subtracted_variance_pct"]:.2f}%\nInteraction variance = {steinsiek_stats["two_way_variance_pct"]["interaction_pct"]:.2f}%',transform=ax.transAxes,fontsize=7.0)
save(fig,'SuppFigS19_Steinsiek2014_predictive_transfer.png')

# S20: diagnostics for predictive transfer from glucose to maltose.
fig,axes=plt.subplots(1,2,figsize=(9.8,4.0),constrained_layout=True)
ax=axes[0]
g=weu_glc.sort_values('oxygen_in_mmol_L_h')
ax.plot(g.oxygen_in_mmol_L_h,g.q_ethanol_isotonic,lw=1.3,color='black',label='Monotonic response')
measured=~g.ethanol_out_censored_lt_mM.notna()
ax.scatter(g.loc[measured,'oxygen_in_mmol_L_h'],g.loc[measured,'q_ethanol'],s=30,label='Measured')
ax.scatter(g.loc[~measured,'oxygen_in_mmol_L_h'],g.loc[~measured,'q_ethanol'],s=34,marker='v',label='Ethanol not detected')
ax.set_xlabel('O$_2$ feed (mmol l$^{-1}$ h$^{-1}$)'); ax.set_ylabel('Net ethanol production\n(mmol gDW$^{-1}$ h$^{-1}$)'); ax.legend(frameon=False,fontsize=6.5); panel_title(ax,'a','Glucose response used for predictive transfer')
ax=axes[1]
lim=[0,9]; ax.plot(lim,lim,ls='--',lw=1,color='black')
ax.scatter(weu_held.q_ethanol,weu_held.q_pred,s=38)
for _,rr in weu_held.iterrows(): ax.annotate(f'{rr.oxygen_in_mmol_L_h:g}',(rr.q_ethanol,rr.q_pred),xytext=(3,3),textcoords='offset points',fontsize=6.2)
ax.set_xlim(lim); ax.set_ylim(lim); ax.set_xlabel('Observed maltose net ethanol production'); ax.set_ylabel('Predicted maltose net ethanol production'); panel_title(ax,'b','Held-out maltose states')
ax.text(.05,.95,f'r = {weu_stats["r"]:.3f}\n$R^2_{{pred}}$ = {weu_stats["predictive_r2"]:.3f}\nRMSE = {weu_stats["rmse_mmol_gDW_h"]:.2f}',transform=ax.transAxes,va='top',fontsize=7.2)
save(fig,'SuppFigS20_Weusthuis1994_predictive_transfer.png')

print('Created publication figures in',OUT)
